### ISSUE TITLE
Geode support?

### ISSUE THREAD

**Issue by I-like-Portal-2** [Prevter/GDOpenHack#32]
This is the closest thing to free megahack i've seen yet, and it's awesome! But, unfortunately, it doesn't work with geode for obvious reasons. The only mod menu there is on geode is Prism, which is worse than openhack imo. Will there ever be a .geode version for this mod? Thanks in advance!

**Comment by Prevter** [comment]
Geode support is planned.
I already have a beta version of openhack running on geode, but it's completely unstable due to geode having a lot of issues.

There is also a trade of, because geode doesn't support all Geometry Dash versions, while openhack can be launched on 2.200-2.204 without any issues. That also goes for future game updates, as with geode, there will be a time window where mod won't support the new version (not an issue with current setup).

I guess the best case scenario is to have two separate branches, like it's currently done for megahack.

**Comment by Prevter** [comment]
Pushed first commit into the [geode branch](https://github.com/Prevter/GDOpenHack/tree/geode). It runs, but there are still issues with some methods, which need to be hooked manually. I think I will finish it Soon™.

**Comment by Rustring** [comment]
How can I install it?

**Comment by Prevter** [comment]
It's still very unstable, so right now the only option is to build it yourself.
I will try to finish today or tomorrow.

**Comment by I-like-Portal-2** [comment]
That was fast! Thank you!

**Comment by Prevter** [comment]
Done!
Releases page now contains a `.geode` file available for download.
It's also available for download through "Download" tab in Geode menu.
