### ISSUE TITLE
[Bug] Startpos switcher on editor after playing a level 

### ISSUE THREAD

**Issue by ItzMarioPlayz12** [Prevter/GDOpenHack#40]
**Describe the bug**
(Geode SDK) AFter using a startpos switcher in a level, when you get in the editor its still there. And when you try to use it the game crashes

**To Reproduce**
1. turn on startpos switcher
2. Play a level from the create tab
3. pause and go to editor
4. try click the keybinds of startpos switcher (Q or E)

**Expected behavior**
It should change to the other startpos'

**Screenshots**
![image](https://github.com/Prevter/GDOpenHack/assets/110222477/8733dfe3-c7ee-43a4-886b-087bfc54502b)
**Recordings**
https://drive.google.com/file/d/1-ybRzIlDba3uoEwzgWG46W9U36RX66EW/view?usp=sharing

**Comment by Prevter** [comment]
The reason for this issue is that mod doesn't delete the pointer to the PlayLayer when it's being closed, because hook for destructor isn't being called.
Waiting for the [PlayLayer::~PlayLayer binding](https://github.com/geode-sdk/bindings/pull/146) to be accepted by geode team, which would fix the issue.

**Comment by Prevter** [comment]
Made a working workaround, so this is now fixed
