### ISSUE TITLE
Set 0.00x Game Speed

### ISSUE THREAD

**Issue by Kacper8698** [Prevter/GDOpenHack#84]
When I Set Game Speed To 0.0x my game froze and i cant load the game and reset openhack data. now I cant use open hack :( . because when i unistall the geode the data of open hack is here with 0.00x speed :(

Comment From The Owner Of OpenHack:

I'm not sure what would be the best option to fix it. The best option I have is to not save speedhack enabled state at all, so that game always launches with speedhack disabled.

You can find config data by pressing Win + R and entering this:
%LocalAppData%/GeometryDash/geode/mods/prevter.openhack and then either editing config.json or removing it completely, which would reset saved settings.

**Comment by qpxit** [comment]
same thing happened to me and i have no idea how to fix it

**Comment by Prevter** [comment]
I'm not sure what would be the best option to fix it. The best option I have is to not save speedhack enabled state at all, so that game always launches with speedhack disabled.

You can find config data by pressing Win + R and entering this:
`%LocalAppData%/GeometryDash/geode/mods/prevter.openhack` and then either editing `config.json` or removing it completely, which would reset saved settings.
